#!/bin/sh
Xvfb :2 &
export DISPLAY=:2
export PATH=/sware/isdd/soft/java/v7u17/linux_x64/jdk1.7.0_17/bin:$PATH
cd /scisoft/jenkins/ub1004_jonathan/squish-4.2.3-java-linux64/bin/
./squishserver &>/$WORKSPACE/serverlog
sleep 1
/scisoft/jenkins/ub1004_jonathan/squish-4.2.3-java-linux64/bin/squishrunner --testsuite /scisoft/jenkins/ub1004_jonathan/workspace/Dawn_squish_tests/org.dawnsci.squishtests/suite_workflows_general/ --testcase tst_loop_example/ --useWaitFor>/$WORKSPACE/squishlog
var1=$(ps -aef |grep squishserver | grep -v grep | awk '{ print $2; }' |  head -1)
kill -9 $var1
var2=$(ps -aef |grep Xvfb | grep -v grep | awk '{ print $2; }' |  head -1)
kill -9 $var2

